app:
  env-vars:
    appName: ${APP_NAME}
    nextPblEnv: ${NEXT_PUBLIC_ENV}
    nextPblBackUrl: ${NEXT_PUBLIC_BACK_URL}
    nextPblBackUrlDev: ${NEXT_PUBLIC_BACK_URL_DEV}
    nextPblBackUrlTest: ${NEXT_PUBLIC_BACK_URL_TEST}
    nextPblFrontUrl: ${NEXT_PUBLIC_FRONT_URL}
    nextPblFrontUrlDev: ${NEXT_PUBLIC_FRONT_URL_DEV}
    nextPblFrontUrlTest: ${NEXT_PUBLIC_FRONT_URL_TEST}
    nextPblSmptFrom: ${NEXT_PUBLIC_SMPT_FROM}
    redisUrl: ${REDIS_URL}

server:
  address: 0.0.0.0
  port: 3000
  tomcat:
    relaxed-query-chars: "[,]"

spring:
  r2dbc:
    url: set_with_ctm_env_loader_cls
    username: set_with_ctm_env_loader_cls
    password: set_with_ctm_env_loader_cls

  main:
    banner-mode: off

  web:
    resources:
      add-mappings: false

  webflux:
    multipart:
      max-in-memory-size: 50MB
      max-disk-usage-per-part: 100MB

  liquibase:
    enabled: true
    change-log: classpath:db/master.yaml

logging:
  level:
    root: WARN
    org.hibernate: WARN
    org.flywaydb: WARN
